context.modules = [
  { name = libpipewire-module-adapter }
  { name = libpipewire-module-protocol-native }
  { name = libpipewire-module-client-node }
  {
    name = libpipewire-module-filter-chain
    args = {
      node.description = MicAdjuster
      filter.graph = {
        nodes = [
          {
            type   = lv2
            # use carla export with settings preset, then fixup lv2:symbol to avoid urls, unfortunately random crashes even this way
            plugin = "file:///usr/local/lib/lv2/CarlaExported/CarlaExported.ttl"
          }
        ]
      }
      capture.props = {
        node.description = PlainMicSink
        # node.passive = true # causes bugs
      }
      playback.props = {
        node.description = AdjustedMicSource
        media.class = Audio/Source
      }
    }
  }
]
